const Data = [
  {
    data: "détruit un objet ou meuble en pratiquant l'acte ?",
    theme: 1,
    mode: 2,
    reponse_0: 'Tu ne bois aucune gorgée, restons sage',
    reponse_1: 'Tu prends 4 gorgées, sauvage',
    reponse_2: 'Si tu as cassé le lit, tu vas boire un demi-verre',
  },
  {
    data: 'utilisé la beuh comme ingrédient de cuisine ?',
    theme: 2,
    mode: 2,
    reponse_0: 'Les épices sont mieux. Rien pour toi.',
    reponse_1: '3 gorgées, chef !',
    reponse_2: '5 gorgées, chef !',
  },
  {
    data: 'connu la Friendzone ?',
    theme: 5,
    mode: 1,
    reponse_0: "Tu vas pas t'en sortir indemne. 3 gorgées",
    reponse_1: '1 gorgée pour ta conquête',
    reponse_2: 'Je compatis alors tu ne prends rien. Distribues 4 gorgées',
  },
  {
    data: 'assommé ou étourdi ton/ta partenaire pendant le sexe ?',
    theme: 1,
    mode: 3,
    reponse_0: 'Encore heureux, aucune gorgée',
    reponse_1: 'Tu vas prendre 4 gorgées, ca va te calmer.',
    reponse_2: 'Tu vas prendre 7 gorgées, ca va te calmer.',
  },
  {
    data: 'fait une plantation de cannabis ?',
    theme: 2,
    mode: 3,
    reponse_0: 'Pas de gorgée pour cette fois-ci.',
    reponse_1: "Tu prends 3 gorgées l'agriculteur",
    reponse_2: 'Tu prends un cul sec si tu fais un potager à coté',
  },
  {
    data: "imprimé ton cul sur l'imprimante ?",
    theme: 4,
    mode: 2,
    reponse_0: 'Une personne aussi sage a droit de distribuer 2 gorgées',
    reponse_1: "J'espère que c'était drôle. 2 gorgées",
    reponse_2: '2 gorgées pour chaque fois',
  },
  {
    data: 'blessé ou été blessé(e) physiquement à cause du sexe ?',
    theme: 1,
    mode: 2,
    reponse_0: 'Ta douceur te fera prendre 2 gorgées',
    reponse_1: 'Bois 2 gorgées de sauvage',
    reponse_2: 'Bois 4 gorgées de sauvage',
  },
  {
    data: "réussi à te perdre lors d'une soirée, à cause de l'alcool ?",
    theme: 2,
    mode: 2,
    reponse_0: 'Félicitations, tu es normal. Prends donc ces 0 gorgées',
    reponse_1: "5 gorgées si t'as pas retrouvé la soirée",
    reponse_2: "Je te fais pas boire. Tu fais n'importe quoi",
  },
  {
    data: "dis à quelqu'un qu'il puait de la gueule ?",
    theme: 4,
    mode: 1,
    reponse_0: "C'est important d'être sincère. Tu bois 2 gorgées",
    reponse_1: 'Tu es une bonne personne. Distribues donc 2 gorgées',
    reponse_2:
      "Tu bois 2 gorgées si tu l'as dit plusieurs fois à la même personne",
  },
  {
    data: 'fini ivre dans un lieu public ?',
    theme: 2,
    mode: 2,
    reponse_0: "Peut-être que tu t'en rappelles juste plus. Pas de gorgée.",
    reponse_1: 'Les bars ont eu raison de toi. 2 gorgées',
    reponse_2: 'Les bars ont eu raison de toi. 4 gorgées',
  },
  {
    data: 'volé dans un magasin ?',
    theme: 4,
    mode: 2,
    reponse_0: 'Une personne aussi honnête a droit de distribuer 4 gorgées',
    reponse_1: "On t'en veux pas mais tu prends 2 gorgées",
    reponse_2: 'Voles 4 gorgées à ton voisin de gauche',
  },
  {
    data: 'simulé au lit ?',
    theme: 1,
    mode: 1,
    reponse_0: 'Je suis fier de toi, distribues 1 gorgée',
    reponse_1: 'Il faut dire les choses... Bois 2 gorgées',
    reponse_2: 'Il faut dire les choses... Bois 4 gorgées pour te décoincer.',
  },
  {
    data: "fait un blackout (oublier une partie ou tout d'une soirée) ?",
    theme: 2,
    mode: 3,
    reponse_0: 'Continues dans cette voie, 0 gorgée',
    reponse_1: "Tu bois 5 gorgées, si tu as oublié comment tu t'es endormi",
    reponse_2: "L'alcool c'est pas de l'eau hein.  Tu bois 2 petites gorgées",
  },
  {
    data: 'embrassé plusieurs personnes en une soirée ?',
    theme: 5,
    mode: 2,
    reponse_0: "Déjà une seule c'est très bien. Comme 1 gorgée",
    reponse_1: "Tu bois 5 gorgées si c'était des gages. Non mais oh",
    reponse_2: 'Tu as du faire des jaloux. Ca sera 5 gorgées pour toi',
  },
  {
    data: 'menti(e) sur ta virginité ',
    theme: 1,
    mode: 1,
    reponse_0: 'Restes humbles. Ne bois pas de gorgées',
    reponse_1: 'Bon, une seule fois, ca va. Bois seulement une gorgée',
    reponse_2: 'Si tu as menti au lycée, tu bois 5 gorgées',
  },
  {
    data: "fini ivre à cause d'un jeu d'alcool ?",
    theme: 2,
    mode: 2,
    reponse_0:
      "Soit tu tiens bien soit t'as de la chance. Dans tout les cas, tu prends 5 gorgées",
    reponse_1: "Je vais t'épargner pour celle-ci. Bois 1 gorgée",
    reponse_2: "Je vais t'épargner pour celle-ci. Distribue 1 gorgée",
  },
  {
    data: 'gardé un sous-vêtement plus de 3 jours ?',
    theme: 3,
    mode: 1,
    reponse_0: 'M./Mme. Propre distribue 2 gorgées',
    reponse_1: 'Bois 2 sales gorgées',
    reponse_2: 'Bois 3 gorgées. Crado.',
  },
  {
    data: 'couché avec un(e) étranger(e) ?',
    theme: 1,
    mode: 2,
    reponse_0: 'Je ne donne rien.',
    reponse_1: 'Un touriste comme toi prends 3 gorgées',
    reponse_2: 'Un touriste comme toi prends 5 gorgées',
  },
  {
    data: "bu un cimetière (mélange horrible d'alcools) ?",
    theme: 2,
    mode: 2,
    reponse_0: 'Tu penses à ton estomac. Tu ne bois pas pour ce tour.',
    reponse_1: 'Tu bois 3 gorgées si tu as vomi après',
    reponse_2: 'Si les cours de chimies te manque autant... Bois 3 gorgées',
  },
  {
    data: 'passé plus de 3 jours sans te laver ?',
    theme: 3,
    mode: 2,
    reponse_0: 'Bravo ! En récompense, voici rien',
    reponse_1: 'Une fois ca va... Bois 1 gorgée',
    reponse_2: "Si tu t'es pas lavé aujourd'hui, tu prends 4 gorgées",
  },
  {
    data: 'été surpris(e) en train de te masturber ?',
    theme: 1,
    mode: 1,
    reponse_0: 'Bien joué à toi. Tu prends 2 gorgées puisque tu fais le malin',
    reponse_1: 'Coup dur... je te laisse tranquille.',
    reponse_2: 'Si tu assures pas tes arrières aussi. 2 gorgées pour toi',
  },
  {
    data: "regretté d'être allé(e) à une soirée ?",
    theme: 2,
    mode: 1,
    reponse_0: 'On est tous super content pour toi.',
    reponse_1: "Si c'est cette soirée, tu bois 2 gorgées et tu t'en vas",
    reponse_2:
      "Si cette soirée en fait partie, tu bois 2 gorgées et tu t'en vas",
  },
  {
    data: 'eu un "date" grâce à une appli de rencontre ?',
    theme: 5,
    mode: 2,
    reponse_0: 'Tu préfères le vrai. Comme 2 vraies gorgées.',
    reponse_1: "Si c'était nul.. Tu distribues 3 gorgées",
    reponse_2: "J'espère que ca était concluant. Je te donne 3 gorgées",
  },
  {
    data: "pété pendant l'acte ?",
    theme: 1,
    mode: 2,
    reponse_0: 'Tu fais les choses bien. Distribues 1 gorgée',
    reponse_1: "Tant que t'as pas fait exprès...Ca passe. 2 gorgées pour toi",
    reponse_2: "Un vrai tue l'amour. prends 5 gorgées",
  },
  {
    data: "fait des soirées dans l'optique de te bourrer la gueule ?",
    theme: 2,
    mode: 1,
    reponse_0: "Si tu n'aimes pas ça alors je ne te fais pas boire.",
    reponse_1: 'Une seule fois ? Vraiment ? Prends ces 6 gorgées',
    reponse_2: "Toi c'est toutes les soirées. Je te donne 2 gorgées",
  },
  {
    data: "pratiqué l'acte sans faire de préliminaires ?",
    theme: 1,
    mode: 2,
    reponse_0: 'Une personne aussi douce ne boit pas',
    reponse_1: "Si c'est une seule fois, c'est qu'une seule gorgée",
    reponse_2: 'Tu ne perds pas ton temps toi. Tu bois 2 gorgées ',
  },
  {
    data: 'été bourré(e) ou défoncé(e) au travail ou pendant les cours ?',
    theme: 2,
    mode: 2,
    reponse_0:
      'Une personne aussi sérieuse a besoin de se décontracter, tu bois 3 gorgées',
    reponse_1:
      'Tu sais, il y a un temps pour tout...Et là il est temps de boire 3 gorgées',
    reponse_2:
      'Tu sais, il y a un temps pour tout...Et là il est temps de boire 5 gorgées',
  },
  {
    data: 'été dragué(e) par un(e) inconnu(e) ?',
    theme: 5,
    mode: 1,
    reponse_0:
      "T'as juste pas eu de chance c'est tout ! Tu sais quoi, donnes 3 gorgées à qui tu veux",
    reponse_1:
      "Super... et bien, ca n'a aucun rapport mais tu échanges ton verre avec la personne en face de toi",
    reponse_2: 'Tu bois 3 gorgées avant de prendre la grosse tête',
  },
  {
    data: "confondu un nom de partenaire lors d'un rapport sexuel ?",
    theme: 1,
    mode: 3,
    reponse_0: 'Normal jusque là... Pas de gorgée',
    reponse_1: 'Trop de partenaires, tue les partenaires. 5 gorgées',
    reponse_2: 'Trop de partenaires, tue les partenaires. 8 gorgées',
  },
  {
    data: "perdu exprès à un jeu d'alcool ?",
    theme: 2,
    mode: 1,
    reponse_0: 'Ton fairplay te donne 2 gorgées à distribuer',
    reponse_1: 'Oups alors ! Tu ne refuses donc pas ces 2 gorgées ?',
    reponse_2: 'Oups alors ! Tu ne refuses donc pas ces 4 gorgées ?',
  },
  {
    data: 'mangé tes crottes de nez ?',
    theme: 3,
    mode: 1,
    reponse_0: 'Même pas pour tester ? Bon.. rien pour toi',
    reponse_1:
      "Beaucoup l'ont fait étant petit... Je t'en veux pas, une toute petite gorgée",
    reponse_2: 'Si tu as faim, il faut le dire tu sais. 2 gorgées et 3 chips',
  },
  {
    data: "fait l'amour sur une table ?",
    theme: 1,
    mode: 2,
    reponse_0: 'Un lit est confortable. pas de gorgées',
    reponse_1: " Tu prends 5 gorgées si c'etait une table Ikea",
    reponse_2: 'Carrément un deuxième lit. 4 gorgées',
  },
  {
    data: 'vomi à cause du cannabis ou fait un badtrip ?',
    theme: 2,
    mode: 2,
    reponse_0: "La drogue c'est mal. Mais l'alcool c'est bien. 1 gorgée",
    reponse_1: 'Bah alors ? On tient pas ? 2 gorgées',
    reponse_2:
      'Il faudrait commencer à connaitre ses limites... TU bois 3 gorgées',
  },
  {
    data: 'détruit un bien public ?',
    theme: 4,
    mode: 1,
    reponse_0: 'Le bon sens ne te donne pas de gorgée',
    reponse_1: 'Si tu as déjà fait des graphs, tu bois 4 gorgées',
    reponse_2: 'Je ne veux pas te voir dans la rue toi. Tu prends 4 gorgées',
  },
  {
    data: "pratiqué l'acte dans plusieurs pièces d'une maison en une journée ?",
    theme: 1,
    mode: 3,
    reponse_0: "Sur un lit, c'est deja bien. Tu ne bois rien",
    reponse_1: "Tant que c'était pas dans le grenier. Ca va. Tu bois 2 gorgées",
    reponse_2: 'Et pourquoi pas chez les voisins non plus ? Tu bois 6 gorgées',
  },
  {
    data: 'pris une cuite dès le matin ?',
    theme: 2,
    mode: 3,
    reponse_0:
      "On sait que t'as déjà assez pris de cuite le soir. Pas de gorgée",
    reponse_1:
      'Tu as beau etre matinal, tu as mal. Bois 4 gorgées pour aller mieux',
    reponse_2:
      'Tu as beau etre matinal, tu as mal. Bois 7 gorgées pour aller mieux',
  },
  {
    data: 'été impliqué(e) dans une bagarre ?',
    theme: 4,
    mode: 1,
    reponse_0: 'Bois 2 gorgées en douceur',
    reponse_1: "Si c'était un casse pied. Tu as bien fait ! Tu ne bois rien",
    reponse_2: 'Un vrai taré. Tu bois rien toi.',
  },
  {
    data: "utilisé de la nourriture lors d'un rapport sexuel ?",
    theme: 1,
    mode: 2,
    reponse_0: "Bois 1 gorgée en mangeant un truc. ne t'étouffes pas non plus.",
    reponse_1: "Tu bois 4 gorgées si c'était de la chantilly",
    reponse_2: "Ton partenaire n'est pas une assiette. 4 gorgées",
  },
  {
    data: 'utilisé/inhalé du poppers ?',
    theme: 2,
    mode: 2,
    reponse_0: 'Prends 0 gorgée pour te décontracter',
    reponse_1: 'Tu sens ces 2 gorgées pour toi ?',
    reponse_2: 'Tu sens ces 4 gorgées pour toi ?',
  },
  {
    data: 'mangé de la nourriture pour animaux ?',
    theme: 3,
    mode: 1,
    reponse_0:
      'On ne mange pas les croquettes du chien. On prends plutot 2 gorgées',
    reponse_1:
      "Il faut gouter pour savoir si on aime. Ca s'applique à tout. Pas de gorgée",
    reponse_2: "Non, tu n'es pas un chien. Bois 3 gorgées",
  },
  {
    data: "fait l'amour dans un hamac ",
    theme: 1,
    mode: 2,
    reponse_0: 'Tu préfères peut etre boir 1 gorgée ?',
    reponse_1: 'Tu bois 2 gorgées très douces',
    reponse_2: 'Tu bois 3 gorgées très douces',
  },
  {
    data: 'dormi sur le sol pendant une soirée trop arrosée ?',
    theme: 2,
    mode: 2,
    reponse_0: 'Ta santé est importante alors ne bois rien',
    reponse_1: 'Bois 2 gorgées et une pensée pour ton dos',
    reponse_2: 'Bois 5 gorgées si ton lit va etre le sol cette soirée',
  },
  {
    data: 'utilisé un lavabo ou évier au lieu des toilettes ?',
    theme: 3,
    mode: 2,
    reponse_0:
      "C'est vrai que les toilettes servent pour ça. Distribues 2 gorgées pour ta perspicacité",
    reponse_1: 'Tu bois 2 gorgées. PS : Tu es sale.',
    reponse_2: 'Tu bois 4 gorgées. PS : Tu es sale.',
  },
  {
    data: "pratiqué l'acte avec des chaussettes ?",
    theme: 1,
    mode: 1,
    reponse_0: 'Tu les enlèves à chaque fois ? Tu es sur ? Bois 3 gorgées ',
    reponse_1: "Oui, c'est même normal... Tu ne bois pas",
    reponse_2: "Oui, c'est même normal... Tu ne bois pas",
  },
  {
    data: "confondu et bu de l'eau de vie à la place de l'eau ?",
    theme: 2,
    mode: 2,
    reponse_0:
      "C'est juste une question de chance. C'est tout. Tu ne bois rien veinard",
    reponse_1:
      "C'est dans ces moments là qu'on se rend compte que l'alccol n'est pas de l'eau. Tu bois 2 gorgées",
    reponse_2: "Tu prends 5 gorgées et un rdv chez l'ophtalmo",
  },
  {
    data: "entendu tes parents faire l'amour ?",
    theme: 5,
    mode: 1,
    reponse_0: 'Que ton innocence soit à jamais conservé. Tu bois 3 gorgées.',
    reponse_1: 'Oublies ca vite en buvant une gorgée',
    reponse_2: '... Tu distribues 5 gorgées si tu les as vu',
  },
  {
    data:
      'effectué ou subi un changement de trou par surprise (sodomie surprise quoi...) ?',
    theme: 1,
    mode: 3,
    reponse_0: "Si tu aimes pas l'effet de surprise... Je te fais pas boire",
    reponse_1: 'Mieux que le père noël. Tu gagnes 4 gorgées en cadeau',
    reponse_2: 'Mieux que le père noël. Tu gagnes 7 gorgées en cadeau',
  },
  {
    data: "vomi à cause de l'alcool sur quelqu'un pendant l'acte ",
    theme: 2,
    mode: 3,
    reponse_0: "T'es pas drôle quand même. Je te donne pas de gorgées a boire",
    reponse_1: 'Un detraqué mental. Tu bois 4 gorgées',
    reponse_2: 'Le détraqué mental boit 8 gorgées',
  },
  {
    data: 'réalisé un beer pong dans un bar ?',
    theme: 2,
    mode: 2,
    reponse_0:
      "Oui.. c'est juste que t'as pas osé parce que tu sais que tu vas perdre. Pas de gorgées",
    reponse_1: "Tu bois 3 gorgées du verre d'en face",
    reponse_2: "Tu bois 5 gorgées du verre d'en face",
  },
  {
    data: "mangé une feuille de canabis dans l'optique de te défoncer à fond",
    theme: 2,
    mode: 3,
    reponse_0:
      "Les joints font l'affaire tu es intelligent. Je te fais pas boire",
    reponse_1: "Un vrai cheval, t'en as plus rien à foutre. Tu bois 5 gorgées",
    reponse_2: "Un vrai cheval, t'en as plus rien à foutre. Tu bois 7 gorgées",
  },
  {
    data: 'réalisé un plan à 4',
    theme: 1,
    mode: 3,
    reponse_0:
      "Tu préfères un mario kart avec tes amis qu'un plan à 4. C'est compréhensible. Tu ne bois pas",
    reponse_1:
      "On parlait de sexe hein ? T'es sur de toi ? Bon ben bois 5 gorgées",
    reponse_2: "Tu bois 7 gorgées sauf si c'était avec ta famille",
  },
  {
    data: 'participé à un gang bang ?',
    theme: 1,
    mode: 3,
    reponse_0: 'Plus on est, plus on rit non ? Bon ok tu bois rien. ',
    reponse_1: "Tu bois 7 gorgées si tu étais avec des amis d'efance",
    reponse_2: 'Tu nous donneras ta chaîne porno et tu bois 7 gorgées',
  },
  {
    data: 'mangé de la bougie ?',
    theme: 3,
    mode: 3,
    reponse_0: "D'accord tu bois pas, a part si tu lèches les bougies.",
    reponse_1: 'Tu bois 6 gorgées si ca sentait la fraise',
    reponse_2: "C'est si bon que ça la cire ? BougieMan boit 8 gorgées",
  },
  {
    data:
      "effectué ou subi une biffle si forte qu'elle a laissé une trace toute la nuit",
    theme: 1,
    mode: 3,
    reponse_0:
      'Mise à part de sauter depuis 3 mètres. Je vois pas comment faire. Tu ne bois pas.',
    reponse_1: 'Tu bois 4 gorgées. +2 si la trace se voyait dans le noir',
    reponse_2: 'Tu bois 6 gorgées. +2 si la trace se voyait dans le noir',
  },
  {
    data: 'réalisé des cocktails maisons ?',
    theme: 2,
    mode: 1,
    reponse_0: 'Tu bois 2 gorgées de ton vieux mélange vodka pomme',
    reponse_1: 'Tu bois 1 gorgée barman',
    reponse_2: 'Tu bois 3 gorgées barman',
  },
  {
    data: 'fait un coma éthylique ?',
    theme: 2,
    mode: 3,
    reponse_0:
      "Eh bien je ne vais pas t'aider à en faire un donc tu ne boos rien.",
    reponse_1:
      "Eh oui, l'alcool pur c'est pas du sirop. Tu bois 5, gorgées de ton sirop",
    reponse_2:
      'Plutot absinthe ou gnole ? Distribues 3 gorgées au lieu de boire toi',
  },
  {
    data: 'pris de la cocaïne ?',
    theme: 2,
    mode: 3,
    reponse_0: 'Tu ne bois pas, tu ne consomme pas ',
    reponse_1: 'Tu prendras 4 gorgées après ton rail',
    reponse_2: 'Tu prendras 7 gorgées après ton rail',
  },
  {
    data: 'recu du vomi au visage ?',
    theme: 3,
    mode: 3,
    reponse_0: 'Tu recois 2 gorgées à la place',
    reponse_1: "Tu distribues 4 gorgées, c'est le plaisir de recevoir",
    reponse_2: "Tu distribues 6 gorgées, c'est le plaisir de recevoir",
  },
  {
    data: 'coulé une douille ?',
    theme: 2,
    mode: 2,
    reponse_0: 'Fais plutôt couler deux gorgées dans ton gosier',
    reponse_1: 'Tu bois une gorgée pour éviter la foncedalle',
    reponse_2: 'Tu bois 3 gorgées pour éviter la foncedalle',
  },
  {
    data: 'fumé de la weed ?',
    theme: 2,
    mode: 1,
    reponse_0: 'Tu as ma bonté divine. Tu peux distribuer 3 gorgées',
    reponse_1: 'Un pti bedo ne fait pas de mal. Une gorgée non plus',
    reponse_2: 'Tu vas me fumer ces 3 gorgées ',
  },
  {
    data: 'volé un panneau de signalisation ?',
    theme: 4,
    mode: 3,
    reponse_0:
      "Félicitations, tu n'es pas fou, tu bois tout de même cette gorgée",
    reponse_1: "Tu bois 8 gorgées si tu l'as encore chez toi",
    reponse_2:
      'Tu fais une collection ou quoi ? Tu distribues 4 gorgées et un de tes panneaux',
  },
  {
    data: 'réalisé une sextape ?',
    theme: 1,
    mode: 2,
    reponse_0: 'Même pas en selfie ? Bon bah tu bois pas...',
    reponse_1: 'Notre acteur de sexe boit 3 gorgées',
    reponse_2: "Tu gagnes 6 gorgées et je m'abonne à ta chaîne",
  },
  {
    data: 'utilisé des préservatifs arômatisé ou phosporescent ?',
    theme: 1,
    mode: 2,
    reponse_0: 'Préservatifs natures ya que ça de vrai. Tu ne bois pas',
    reponse_1:
      "Si c'était pour tenter de faire un sabre laser, tu bois 4 gorgées",
    reponse_2: "Tu bois 5 gorgées si t'as déjà essayé fruit de la passion",
  },
  {
    data: "fait des déclarations d'amitié totalement bourré ?",
    theme: 2,
    mode: 1,
    reponse_0: "Je te donne 3 gorgées pour t'aider",
    reponse_1: "Ca prouve que t'es un bon. Tu distribues une gorgée",
    reponse_2: "Ca prouve que t'es un bon. Tu distribues 3 gorgées",
  },
  {
    data: 'été dragué dans une boite de nuit ?',
    theme: 5,
    mode: 2,
    reponse_0: 'Après si tu es jamais alle en boite de nuit... Tu ne bois pas ',
    reponse_1: 'Tu bois 2 gorgées coquin va !',
    reponse_2: 'Tu bois 4 gorgées, coquin va ! ',
  },
  {
    data: "pris des médicaments juste parce qu'ils avaient bon goût",
    theme: 3,
    mode: 1,
    reponse_0: 'Oui bah je pense que tu préfères 3 gorgées',
    reponse_1:
      'On sait que tu as bu du sirop pour la toux. Bois plutôt une gorgée',
    reponse_2:
      'On sait que tu as bu du sirop pour la toux. Bois plutôt 3 gorgées',
  },
  {
    data: 'fait 3 soirées différentes en une semaine ?',
    theme: 5,
    mode: 3,
    reponse_0: 'Profites de cette soirée déjà. Bois 2 gorgées',
    reponse_1:
      'Tu profites bien de la vie. Distribues ta bonne humeur et 3 gorgées',
    reponse_2:
      'Tu profites bien de la vie. Distribues ta bonne humeur et 5 gorgées',
  },
  {
    data: "dormi dans une baignoire lors d'une soirée",
    theme: 3,
    mode: 2,
    reponse_0: "Tu n'as pas connu des jours de misère... Ne bois pas ",
    reponse_1:
      "C'est toujours mieux que dormir par terre. Baignes toi de deux gorgées",
    reponse_2:
      'Tu préfères presque dormir dans la baignoire. Baignes toi dans 3 gorgées',
  },
  {
    data: 'réalisé ou reçu un anuslingus',
    theme: 1,
    mode: 3,
    reponse_0:
      'Ca peut effrayer mais des fois il faut foncer. Bois 1 gorgée de vigueur',
    reponse_1:
      "Tu aimes l'aventure ? Tu aimes boire ? Alors bois ces 3 gorgées",
    reponse_2:
      "Tu aimes l'aventure ? Tu aimes boire ? Alors bois ces 6 gorgées",
  },
  {
    data: 'mangé un spacecake ?',
    theme: 2,
    mode: 2,
    reponse_0: 'Tu ne bois rien',
    reponse_1: 'Tu vas boire 2 gorgées à cause de ta gourmandise',
    reponse_2: 'Tu vas boire 4 gorgées à cause de ta gourmandise',
  },
  {
    data: 'pété bruyamment en public',
    theme: 3,
    mode: 2,
    reponse_0: 'Un grand controle de soi même. Distribues 1 gorgées',
    reponse_1: 'Ton pti pet te fait prendre une gorgée',
    reponse_2: 'Bois 3 gorgées pour la disparition de ta dignité',
  },
  {
    data: 'pété au visage de ton ou ta partenaire',
    theme: 3,
    mode: 3,
    reponse_0: 'On ne fait pas ca. ne bois pas',
    reponse_1: "On va dire que t'as pas fait exprès. Bois 2 gorgées",
    reponse_2: "Tu bois 6 gorgées si tes amis trouvent que t'es beauf",
  },
  {
    data: 'réussi à pécho dans un bar ?',
    theme: 5,
    mode: 2,
    reponse_0: "Tu sais ce qu'il te reste à faire. Bois une gorgée",
    reponse_1: 'Le tombeur distribue 2 gorgées',
    reponse_2: 'Le tombeur distribue 4 gorgées',
  },
  {
    data: "menti sur les causes d'une rupture ? ",
    theme: 4,
    mode: 1,
    reponse_0: "Une personne de confiance n'a pas besoin de boire.",
    reponse_1: 'Dillue ta fierté dans ces 2 gorgées',
    reponse_2: 'Dilleu ta fierté dans ces 4 gorgées',
  },
  {
    data: 'dansé du logobi ou la tecktonik?',
    theme: 4,
    mode: 1,
    reponse_0: 'Tu as raté des danses endiablées. Bois 2 gorgées',
    reponse_1:
      "Il faut bien tester pour savoir que c'était archi nul. Je ne te fais pas boire",
    reponse_2:
      "TULU, TULUTUTU TU TURU. Si t'as la musqiue tu distribues 5 gorgées",
  },
  {
    data: 'couché avec une personne de plus ou de moins de 4 ans ?',
    theme: 1,
    mode: 3,
    reponse_0: 'Il y a des limites. Ne bois aps',
    reponse_1: "Tu bois 4 gorgées si l'un était mineur et l'autre majeur.",
    reponse_2: '.juste bois, autant que tu veux',
  },
  {
    data: 'fait un pet foireux ?',
    theme: 3,
    mode: 1,
    reponse_0: "T'as juste eu de la chance. Bois 2 gorgées",
    reponse_1: 'Aie. La surprise. Bah surprise, tu bois pas',
    reponse_2:
      "Tu peux te faire avoir une fois mais là t'es juste con. Bois 4 gorgées",
  },
  {
    data: "utilisé des légumes pour simuler une pénétration lors de l'acte ?",
    theme: 1,
    mode: 3,
    reponse_0: 'Pas trop légume.. Tu ne bois pas.',
    reponse_1: "Tu bois 3 gorgées si c'était du bio",
    reponse_2: "Tu bois 5 gorgées si c'était du bio",
  },
  {
    data: "Friendzoné quelqu'un ?",
    theme: 4,
    mode: 2,
    reponse_0: 'Et bien je te donne le droit de donner deux gorgées',
    reponse_1: 'Tu as du faire preuve de courage.. Distribues une gorgée',
    reponse_2: 'Tu as du faire preuve de courage.. Distribues deux gorgées',
  },
];

export default Data;
